### PR TITLE
Use --fix-missing to update apt (and don't modify apt sources.list)

### PR DESCRIPTION
**Pull request by DracoBlue**
Otherwise we run into problems, that python cannot be installed properly.

### CODE REVIEW

**Comment by Sebastian-Fitzner** [comment]
Das kann ja [~~[]()]()

**Comment by DracoBlue** [comment]
@Sebastian-Fitzner hmm?

**Comment by Sebastian-Fitzner** [comment]
Sry, my daughter(2 years) had my phone in hands. When i got my laptop i will delete The comment above... Sry, sry, sry😅

**Comment by DracoBlue** [comment]
Hehe :) No problem!

**Pull request closed without merging**
